#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

/**
 * Hook template as Node script - works on all platforms including Windows/JGit
 * Using #!/usr/bin/env node allows Git to execute this directly with Node
 */
// Hook template for Unix (macOS, Linux)
const HOOK_TEMPLATE = `#!/usr/bin/env node
// Pre-commit hook - runs Prettier on staged files
// Generated by install.js

const { execSync } = require("child_process");
const path = require("path");

// Get git root directory
const gitRoot = execSync("git rev-parse --show-toplevel", { encoding: "utf8" }).trim();

// Load and run the formatter script
const formatterPath = path.join(gitRoot, "scripts", "pre-commit", "formatter.js");

try {
  const formatter = require(formatterPath);
  formatter.runPreCommit();
} catch (error) {
  console.error("Pre-commit hook failed:", error.message);
  process.exit(1);
}
`;

// Hook template for Windows (JGit compatible)
const HOOK_TEMPLATE_WIN = `@echo off
:: Pre-commit hook for Windows - runs Prettier on staged files
:: Generated by install.js

:: Get git root directory
for /f "delims=" %%i in ('git rev-parse --show-toplevel') do set GIT_ROOT=%%i

:: Run the formatter script with Node
node "%GIT_ROOT%\\scripts\\pre-commit\\formatter.js"
`;

/**
 * Gets the paths for hook installation
 * @param {string} baseDir - Base directory (usually __dirname)
 * @returns {Object} Object with gitRoot, hooksDir and preCommitHook paths
 */
function getHookPaths(baseDir) {
  const gitRoot = path.join(baseDir, "../..");
  const hooksDir = path.join(gitRoot, ".git", "hooks");
  const preCommitHook = path.join(hooksDir, "pre-commit");
  const preCommitHookWin = path.join(hooksDir, "pre-commit.cmd");
  return { gitRoot, hooksDir, preCommitHook, preCommitHookWin };
}

/**
 * Ensures the hooks directory exists
 * @param {string} hooksDir - Path to hooks directory
 * @param {Object} fsModule - Filesystem module (mockable for tests)
 */
function ensureHooksDir(hooksDir, fsModule = fs) {
  if (!fsModule.existsSync(hooksDir)) {
    fsModule.mkdirSync(hooksDir, { recursive: true });
  }
}

/**
 * Writes the hook to file
 * @param {string} hookPath - Path to hook file
 * @param {string} content - Hook content
 * @param {Object} fsModule - Filesystem module (mockable for tests)
 */
function writeHook(hookPath, content, fsModule = fs) {
  fsModule.writeFileSync(hookPath, content, { mode: 0o755 });
}

/**
 * Checks if a hook is already installed
 * @param {string} hookPath - Path to hook file
 * @param {Object} fsModule - Filesystem module (mockable for tests)
 * @returns {boolean} true if hook exists
 */
function hookExists(hookPath, fsModule = fs) {
  return fsModule.existsSync(hookPath);
}

/**
 * Reads the content of an existing hook
 * @param {string} hookPath - Path to hook file
 * @param {Object} fsModule - Filesystem module (mockable for tests)
 * @returns {string} Hook content
 */
function readHook(hookPath, fsModule = fs) {
  return fsModule.readFileSync(hookPath, "utf8");
}

/**
 * Installs the pre-commit hook
 * @param {Object} options - Options
 * @param {string} options.baseDir - Base directory
 * @param {Object} options.fsModule - Filesystem module (mockable for tests)
 * @param {Function} options.log - Logging function
 * @returns {Object} Installation result
 */
function installHooks(options = {}) {
  const { baseDir = __dirname, fsModule = fs, log = console.log } = options;

  const { hooksDir, preCommitHook, preCommitHookWin } = getHookPaths(baseDir);

  try {
    log("Installing git hooks...");

    ensureHooksDir(hooksDir, fsModule);

    // Install Unix hook (macOS, Linux)
    writeHook(preCommitHook, HOOK_TEMPLATE, fsModule);

    // Install Windows hook (.cmd for JGit compatibility)
    writeHook(preCommitHookWin, HOOK_TEMPLATE_WIN, fsModule);

    log("Git hooks installed successfully.");
    log("Unix hook:", preCommitHook);
    log("Windows hook:", preCommitHookWin);

    return {
      success: true,
      hookPath: preCommitHook,
      hookPathWin: preCommitHookWin,
    };
  } catch (error) {
    log("Failed to install git hooks:", error.message);
    return { success: false, error: error.message };
  }
}

// Export for tests
module.exports = {
  HOOK_TEMPLATE,
  HOOK_TEMPLATE_WIN,
  getHookPaths,
  ensureHooksDir,
  writeHook,
  hookExists,
  readHook,
  installHooks,
};

// Only execute when called directly
if (require.main === module) {
  const result = installHooks();
  if (!result.success) {
    process.exit(0); // Don't fail npm install
  }
}
