
package de.intranda.digiverso.presentation;

/*
DO NOT
CHANGE THIS FILE, IT'S GENERATED BY ANT!
*/
public class Version {
    public final static String VERSION = "intranda viewer-3.2";
    public final static String BUILDVERSION = "fda8680";
    public final static String BUILDDATE = "20170829";
}
