
			package de.intranda.digiverso.presentation;
			/*
			DO NOT
			CHANGE THIS FILE, IT'S GENERATED BY ANT!
			*/
			public class Version {
			public final static String VERSION = "Goobi viewer-3.4";
			public final static String BUILDVERSION = "d27b99e";
			public final static String BUILDDATE = "20190403";
			}
		