
			package de.intranda.digiverso.presentation;
			/*
			DO NOT
			CHANGE THIS FILE, IT'S GENERATED BY ANT!
			*/
			public class Version {
			public final static String VERSION = "Goobi viewer-3.2";
			public final static String BUILDVERSION = "d48e364";
			public final static String BUILDDATE = "20180322";
			}
		