/**
 * This file is part of the Goobi viewer - a content presentation and management application for digitized objects.
 *
 * Visit these websites for more information.
 *          - http://www.intranda.com
 *          - http://digiverso.com
 *
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package de.intranda.digiverso.presentation.servlets.openid;

import java.io.IOException;
import java.nio.charset.Charset;
import java.util.Date;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.codec.binary.Base64;
import org.apache.commons.lang.StringUtils;
import org.apache.oltu.oauth2.client.OAuthClient;
import org.apache.oltu.oauth2.client.URLConnectionClient;
import org.apache.oltu.oauth2.client.request.OAuthBearerClientRequest;
import org.apache.oltu.oauth2.client.request.OAuthClientRequest;
import org.apache.oltu.oauth2.client.response.GitHubTokenResponse;
import org.apache.oltu.oauth2.client.response.OAuthAccessTokenResponse;
import org.apache.oltu.oauth2.client.response.OAuthAuthzResponse;
import org.apache.oltu.oauth2.client.response.OAuthResourceResponse;
import org.apache.oltu.oauth2.client.validator.TokenValidator;
import org.apache.oltu.oauth2.common.OAuth;
import org.apache.oltu.oauth2.common.OAuthProviderType;
import org.apache.oltu.oauth2.common.error.OAuthError;
import org.apache.oltu.oauth2.common.exception.OAuthProblemException;
import org.apache.oltu.oauth2.common.exception.OAuthSystemException;
import org.apache.oltu.oauth2.common.message.types.GrantType;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.sun.xml.internal.ws.util.HandlerAnnotationProcessor;

import de.intranda.digiverso.presentation.controller.DataManager;
import de.intranda.digiverso.presentation.exceptions.DAOException;
import de.intranda.digiverso.presentation.exceptions.IndexUnreachableException;
import de.intranda.digiverso.presentation.exceptions.PresentationException;
import de.intranda.digiverso.presentation.managedbeans.UserBean;
import de.intranda.digiverso.presentation.managedbeans.utils.BeanUtils;
import de.intranda.digiverso.presentation.model.search.SearchHelper;
import de.intranda.digiverso.presentation.model.security.authentication.AuthenticationProviderException;
import de.intranda.digiverso.presentation.model.security.authentication.IAuthenticationProvider;
import de.intranda.digiverso.presentation.model.security.authentication.IOAuthResponseListener;
import de.intranda.digiverso.presentation.model.security.authentication.OpenIdProvider;
import de.intranda.digiverso.presentation.model.security.user.User;
import de.intranda.digiverso.presentation.servlets.utils.ServletUtils;

/**
 * OpenID Connect business logic.
 */
public class OAuthServlet extends HttpServlet {

    private static final long serialVersionUID = 6279885446798463881L;

    private static final Logger logger = LoggerFactory.getLogger(OAuthServlet.class);

    public static final String URL = "oauth";

    /**
     * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        doPost(request, response);
    }

    /**
     * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

        // Apache Oltu
        Optional<User> user = Optional.empty();
        try {
            OAuthAuthzResponse oar = OAuthAuthzResponse.oauthCodeAuthzResponse(request);
            // Confirm that the state received from the provider matches the state generated by the viewer
            IOAuthResponseListener listener = DataManager.getInstance().getOAuthResponseListener();
            for (OpenIdProvider provider : listener.getProviders()) {
                try {
                    user = handleResponse(oar, provider, request, response);
                    if (user.isPresent()) {
                        listener.unregister(provider);
                        break;
                    }
                } catch (OAuthProblemException e) {
                    if (e.getMessage().startsWith("access_denied")) {
                        logger.debug("User aborted login");
                    } else {
                        logger.error(e.getMessage(), e);
                    }
                    listener.unregister(provider);
                } catch (OAuthSystemException | ParseException e) {
                    logger.error(e.getMessage(), e);
                    listener.unregister(provider);
                    //            response.sendError(HttpServletResponse.SC_UNAUTHORIZED, "OpenID Connect login failed");
                } catch (DAOException e) {
                    logger.debug("DAOException thrown here: {}", e.getMessage());
                    response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Database offline");
                    listener.unregister(provider);
                    return;
                } catch (AuthenticationProviderException e) {
                    logger.debug("AuthenticationProviderException thrown here: {}", e.getMessage());
                    response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, e.getMessage());
                    listener.unregister(provider);
                    return;
                }
            }
        } catch (OAuthProblemException e) {
            if (e.getMessage().startsWith("access_denied")) {
                logger.debug("User aborted login");
            } else {
                logger.error(e.getMessage(), e);
            }
        }

        // If a redirect URL is set, redirect there
//        UserBean ub = BeanUtils.getUserBean();
//        if (ub != null) {
//            if (StringUtils.isNotEmpty(ub.getRedirectUrl())) {
//                logger.debug("Redirecting to " + ub.getRedirectUrl());
//                try {
//                    response.sendRedirect(ub.getRedirectUrl());
//                    return;
//                } finally {
//                    ub.setRedirectUrl(null);
//                }
//            }
//            if (user.isPresent()) {
//                try {
//                    String redirect = ub.setupUser(user.get(), request);
//                    if(redirect == null) {
//                        return;
//                    } else if(!"pretty:user".equals(redirect)) {      
//                        response.sendRedirect(redirect);
//                        return;
//                    } 
//                } catch (DAOException | IndexUnreachableException | PresentationException e) {
//                    logger.debug("Exception thrown here: {}", e.getMessage());
//                    response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, e.getMessage());
//                    return;
//                }
//            }
//        }

//        response.sendRedirect(ServletUtils.getServletPathWithHostAsUrlFromRequest(request) + "/user/");
    }

    private Optional<User> handleResponse(OAuthAuthzResponse oar, OpenIdProvider provider, HttpServletRequest request, HttpServletResponse response)
            throws DAOException, OAuthProblemException, OAuthSystemException, ParseException, AuthenticationProviderException {
        if (provider.getoAuthState() == null || !oar.getState().equals(provider.getoAuthState())) {
            return Optional.empty();
            //            logger.error("Received invalid state token.");
            //            response.sendError(HttpServletResponse.SC_UNAUTHORIZED, "Received invalid state token.");
        }

        // Send access token request (Google)
        OAuthClientRequest oAuthTokenRequest = null;
        switch (provider.getName().toLowerCase()) {
            case "google":
                oAuthTokenRequest = OAuthClientRequest.tokenProvider(OAuthProviderType.GOOGLE)
                        .setGrantType(GrantType.AUTHORIZATION_CODE)
                        .setClientId(provider.getClientId())
                        .setClientSecret(provider.getClientSecret())
                        .setRedirectURI(ServletUtils.getServletPathWithHostAsUrlFromRequest(request) + "/" + URL)
                        .setCode(oar.getCode())
                        .buildBodyMessage(); {
                OAuthClient oAuthClient = new OAuthClient(new URLConnectionClient());
                OAuthAccessTokenResponse oAuthTokenResponse = oAuthClient.accessToken(oAuthTokenRequest);
                if (oAuthTokenResponse != null) {
                    TokenValidator tv = new TokenValidator();
                    tv.validate(oAuthTokenResponse);
                    provider.setoAuthAccessToken(oAuthTokenResponse.getAccessToken());
                    String idTokenEncoded = (oAuthTokenResponse.getParam("id_token"));
                    String[] idTokenEncodedSplit = idTokenEncoded.split("[.]");
                    if (idTokenEncodedSplit.length != 3) {
                        logger.error("Wrong number of segments in id_token. Expected 3, found " + idTokenEncodedSplit.length);
                        break;
                    }
                    // String header = new String(new Base64(true).decode(idTokenEncodedSplit[0]), Charset.forName("UTF-8"));
                    String payload = new String(new Base64(true).decode(idTokenEncodedSplit[1]), Charset.forName("UTF-8"));
                    // String signature = idTokenEncodedSplit[2];
                    JSONObject jsonPayload = (JSONObject) new JSONParser().parse(payload);
                    provider.setJsonResponse(jsonPayload);
                    return provider.completeLogin();
                }
            }

                break;
            case "facebook":
                oAuthTokenRequest = OAuthClientRequest.tokenProvider(OAuthProviderType.FACEBOOK)
                        .setGrantType(GrantType.AUTHORIZATION_CODE)
                        .setClientId(provider.getClientId())
                        .setClientSecret(provider.getClientSecret())
                        .setRedirectURI(ServletUtils.getServletPathWithHostAsUrlFromRequest(request) + "/" + URL)
                        .setCode(oar.getCode())
                        .buildQueryMessage(); {
                OAuthClient oAuthClient = new OAuthClient(new URLConnectionClient());
                OAuthAccessTokenResponse oAuthTokenResponse = oAuthClient.accessToken(oAuthTokenRequest, GitHubTokenResponse.class);
                if (oAuthTokenResponse != null) {
                    TokenValidator tv = new TokenValidator();
                    tv.validate(oAuthTokenResponse);
                    provider.setoAuthAccessToken(oAuthTokenResponse.getAccessToken());

                    // Retrieve resources
                    OAuthClientRequest bearerClientRequest = new OAuthBearerClientRequest("https://graph.facebook.com/me")
                            .setAccessToken(oAuthTokenResponse.getAccessToken()).buildQueryMessage();
                    OAuthResourceResponse resourceResponse =
                            oAuthClient.resource(bearerClientRequest, OAuth.HttpMethod.GET, OAuthResourceResponse.class);
                    if (resourceResponse != null) {
                        // logger.debug(resourceResponse.getBody());
                        JSONObject jsonProfile = (JSONObject) new JSONParser().parse(resourceResponse.getBody());
                        provider.setJsonResponse(jsonProfile);
                        return provider.completeLogin();
                    }
                }
            }
                break;
            default:
                // Other providers
                oAuthTokenRequest = OAuthClientRequest.tokenLocation(provider.getUrl() + "/access_token")
                        .setGrantType(GrantType.AUTHORIZATION_CODE)
                        .setClientId(provider.getClientId())
                        .setClientSecret(provider.getClientSecret())
                        .setRedirectURI(ServletUtils.getServletPathWithHostAsUrlFromRequest(request) + "/" + URL)
                        .setCode(oar.getCode())
                        .buildBodyMessage(); {
                OAuthClient oAuthClient = new OAuthClient(new URLConnectionClient());
                oAuthClient.accessToken(oAuthTokenRequest);
            }
        }
        return Optional.empty();
    }

}