name: Build develop branch

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Set up Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Compile Goobi viewer Core
        run: mvn -f goobi-viewer-core/pom.xml clean package -U -B

