name: Publish Javadoc from latest release

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Set up Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Generate Javadoc
        run: mvn -f goobi-viewer-core/pom.xml javadoc:javadoc
      - name: Publish Javadoc on Github pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: goobi-viewer-core/target/reports/apidocs/

