name: Create Release

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/cache@v1
      name: Set up caching
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - uses: actions/checkout@v4
      name: Checkout Goobi viewer Core

    - name: Generate Javadoc
      run: mvn -f goobi-viewer-core/pom.xml javadoc:javadoc

    - name: Publish Javadoc on Github pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: goobi-viewer-core/target/site/apidocs/

